## What system to build the project with? I.e. Setuptools, Wheel, Poetry, etc.
[build-system]
requires = [
    # "uv >= 0.7.20", # Current version as of 2025-July
    "hatchling"
]
build-backend = "hatchling.build"

[project]
# Project information
name = "KKCalc2"
version = "0.8.4"
description = "Kramers-Kronig transforms for optical data."
readme = "README.rst"
license = {file = "LICENSE"}
keywords = ["Kramers-Kronig", "Optical Data", "X-ray", "Spectroscopy", "Transform", "Contrast"]
authors = [
    {name = "Benjamin Watts", email = "benjamin.watts@gmail.com"},
    {name = "Matthew Gebert", email = "mattheuu.gebert@gmail.com"}
]
maintainers = [
    {name = "Matthew Gebert", email="mattheuu.gebert@gmail.com"}
]

# Project compatibility:
requires-python = ">=3.12"
dependencies = [
    "numpy~=2.4.0", # Basic array and matrix operations
    "scipy~=1.17.1", # Used for constants, interpolation and fitting.
]
optional-dependencies.gui = [
    "PyQt6~=6.10", # For GUI
    "matplotlib~=3.10", # For plotting
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]

[project.urls]
# Website, documentation and other continuous integration URLS.
code = "https://github.com/xraysoftmat/kkcalc" # code = "https://github.com/benajamin/kkcalc"
documentation = "https://kkcalc2.readthedocs.io/en/latest/"

# [project.optional-dependencies]
# gui = [
#     "PyQt6~=6.10.0", # For GUI
#     "matplotlib~=3.10.7", # For plotting
# ]

[project.scripts]
# Command line entry points.

[project.gui-scripts]
# GUI entry points for the command line
kkcalc2 = "kkcalc2.__main__:main"
kkcalc2_tr = "kkcalc2.__main__:main_with_traceback"

[dependency-groups]
# Dependency groups for optional dependencies.
all = [
    {include-group = "dev"},
]

dev = [
    {include-group = "gui"}, # Include GUI dependencies in dev
    {include-group = "docs"}, # Include documentation dependencies in dev
    "pre-commit",
    "pytest",
    "python-semantic-release",
    "commitizen",
    "ruff",
    "periodictable >= 2.0.2", # Due to changes in neutron element as zeroth element.
    "PyInstaller", # For building executables
]

gui = [
    "PyQt6~=6.10", # For GUI
    "matplotlib~=3.10", # For plotting
    "pandas~=3.0", # For loading data files
]

docs = [
    "sphinx",
    "sphinx-pyproject",
    "sphinx-copybutton",
    "intersphinx-registry", # to reference other projects in sphinx
    "pydata-sphinx-theme",
    "numpydoc",
    "matplotlib",
]

#######################################################
#############  Package Build configurations  ##########
#######################################################

# Use "hatchling build" as the build command.
[tool.hatch.build]
directory = "./dist" # Output directory for built packages
targets.sdist.include = [
    "kkcalc2/**",
    # "examples/data/**",
]
targets.sdist.exclude = [
    "docs/*",
    "tests/*",
    "kkcalc2/asf_database/db_data/*", # Exclude raw data files from package
    "kkcalc2/asf_database/db_generator_script.py", # Exclude db generator script
]

[tool.hatch.envs.dev]
dependency-groups = ["dev"]
post-install-commands = [
    # Install pre-commit hooks
    "pre-commit install --install-hooks",
]


#######################################################
#############  Pre-commit configurations  #############
#######################################################

## Linting
# Ruff
[tool.ruff] # Same as Black formatting.
line-length = 88
indent-width = 4

[tool.ruff.format] # Same as Black formatting.
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# ------------------- NUMPYDOC -------------------
[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
]
# remember to use single quotes for regex in TOML
exclude = [  # don't report on objects that match any of these regex
    '\.undocumented_method$',
    '\.__repr__$',
    # Ignore gui modules... not part of the API yet.
    '^.*(dialogs).*$',
    '^.*(contrast_viewer).*$',  # Ignore all gui modules
    '^.*(asf_viewer).*$',
    '^.*(asf_modifier).*$',
    '^.*(asf_loader).*$',
    # Add the .py modules here. Packages don't seem to work...
    '^.*(test).*$',
    '^.*(docs).*$',
    # 'test_stoich',
    # 'test_transforms',
    # 'test_models',

]
override_SS05 = [  # override SS05 to allow docstrings starting with these words
    '^Process ',
    '^Assess ',
    '^Access ',
    '^Alias',
]

[tool.commitizen]
update_changelog_on_bump = true
tag_format = "v$major.$minor.$patch$prerelease.$devrelease"

# ---------- Semantic Release for versioning ------------
# Python-Sem-Ver
[tool.semantic_release.branches.main]
match = "(main|master|v2)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
# build_command = "python -m build --sdist --wheel ."
commit_parser = "conventional"
build_command = "pip install uv && uv build --sdist --wheel . --out-dir dist"
commit_message = """
chore(release): Release `core@{version}` [skip ci]
Automatically generated by python-semantic-release
"""
allow_zero_version = true

# Turn this off, as GUI can be built and added to release manually. Cannot build multiple OS programs with PSR.
# assets = ['dist/gui/']

[tool.semantic_release.branches.beta]
# Matches branches with the prefixes 'feat/', 'fix/', or 'perf/'.
# match = "^(feat|Feat|fix|Fix|perf|Perf)/.+"
# Set to match anything other than main/master/v2
match = "^(?!main$|master$|v2$).+"
prerelease = true
prerelease_token = "beta"

[tool.semantic_release.changelog.default_templates]
changelog_file = "docs/CHANGELOG.rst"
output_format = "rst" # or "md" for Markdown format

[tool.semantic_release.changelog]
# Recommended patterns for conventional commits parser that is scope aware
exclude_commit_patterns = [
    '''chore(?:\([^)]*?\))?: .+''',
    '''ci(?:\([^)]*?\))?: .+''',
    '''refactor(?:\([^)]*?\))?: .+''',
    '''style(?:\([^)]*?\))?: .+''',
    '''test(?:\([^)]*?\))?: .+''',
    '''build\((?!deps\): .+)''',
    '''Initial [Cc]ommit.*''',
    '''wip(?:\([^)]*?\))?: .+''',
]

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
# other_allowed_tags = ["build", "chore", "ci", "docs", "style", "refactor", "test"]
# allowed_tags = ["feat", "fix", "perf", "build", "chore", "ci", "docs", "style", "refactor", "test"]
# default_bump_level = 0
parse_squash_commits = true
ignore_merge_commits = true

[tool.semantic_release.publish]
dist_glob_patterns = [
    "dist/*",
    "dist/gui/kkcalc2-*-gui-*/*",
    "dist/docs/*"
]

#######################################################
#############  Sphinx Doc configurations  #############
#######################################################

[tool.sphinx-pyproject]
html_theme = "pydata_sphinx_theme"

[tool.sphinx-pyproject.html_theme_options]
    # ...
    navbar_start = ["navbar-logo"]
    navbar_center = ["navbar-nav"]
    navbar_end = ["theme-switcher", "navbar-icon-links"]
    navbar_persistent = ["search-button"]
    navbar_align = "content"
    show_nav_level = 2
    navigation_depth = 4
    # ...
    secondary_sidebar_items = ["page-toc", "edit-this-page", "sourcelink"]
    # ...
    article_footer_items = []
    #...
    footer_start = ["copyright", "sphinx-version"]
    footer_end = ["theme-version"]
    #...
    show_prev_next = true

# Array item:
[[tool.sphinx-pyproject.html_theme_options.icon_links]]
    name = "GitHub"
    url = "https://github.com/xraysoftmat/kkcalc"
    icon = "fab fa-github-square"
    type = "fontawesome"

[tool.sphinx-pyproject.html_sidebars]
  "**" = ["sidebar-nav-bs", "sidebar-ethical-ads"] # default

[tool.sphinx-pyproject.html_context]
    default_mode = "light"
    default_dark_mode = false
    default_language = "en"
    default_version = "latest"
    display_github = true
    github_user = "xraysoftmat"
    github_repo = "kkcalc2"
    github_version = "main"
    doc_path = "docs"

# Esbonio Sphinx extension for VS Code integration - https://docs.esbon.io
[tool.esbonio.sphinx]
    # buildCommand = ["sphinx-build", "-M", "dirhtml", "./docs", "./docs/_build"]
    buildCommand = ["sphinx-build", "-M", "html", "./docs", "./docs/_build"] # sphinx-build -M html ./docs ./docs/_build
    pythonCommand = ["${venv:kkcalc2}"]
